### ISSUE TITLE
Stalling when reading sparse matrices W/O loading Matrix

### ISSUE THREAD

**Issue by rrydbirk** [HaoZeke/fastMatMR#22]
Thank you for a fantastic tool! It has really sped up my day-to-day work when combining R and Python.

If I do

```
library(fastMatMR)
fmm_to_sparse_Matrix("/path/to/my/sparse/matrix.mtx")
```

it stalls. It seems to read in the matrix (activity on multiple CPUs, memory increases), but when it tries to write it as sparse in memory nothing happens (one core at 100%, no change in memory).

But, if I do

```
library(Matrix)
library(fastMatMR)
fmm_to_sparse_Matrix("/path/to/my/sparse/matrix.mtx")
```

It finishes in seconds, as expected.

```
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fastMatMR_1.0.0.0 Matrix_1.6-1.1   

loaded via a namespace (and not attached):
[1] compiler_4.3.1 tools_4.3.1    grid_4.3.1     lattice_0.21-8
```

**Comment by HaoZeke** [comment]
Sorry for not addressing this earlier, and thanks for the bug report! The issue is that the `sparse` matrix format is being tested is defined within `Matrix` so it needs to be loaded, I will make `Matrix` a hard dependency for the package.

> Thank you for a fantastic tool! It has really sped up my day-to-day work when combining R and Python.

Glad to hear it ^_^
